//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A9_SoftwareEntities3 : DbContext
    {
        public DB_A9_SoftwareEntities3()
            : base("name=DB_A9_SoftwareEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<GROUP> GROUPs { get; set; }
        public DbSet<Group_User> Group_User { get; set; }
        public DbSet<ImageGallery> ImageGalleries { get; set; }
        public DbSet<Lookup> Lookups { get; set; }
        public DbSet<Register> Registers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
