//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public Lookup()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
