//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Contacts = new HashSet<Contact>();
            this.Group_User = new HashSet<Group_User>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage="Please Enter your Username",AllowEmptyStrings=false)]
        public string UserName { get; set; }
        [Required(ErrorMessage="Please Provide your password",AllowEmptyStrings=false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> RoleId { get; set; }
        public bool ISACTIVE { get; set; }
        public string Email { get; set; }
        public Nullable<bool> CanLogin { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> RegisterId { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Group_User> Group_User { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Register Register { get; set; }
    }
}
