//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public GROUP()
        {
            this.Group_User = new HashSet<Group_User>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string GroupMember { get; set; }
        public byte[] LOGO { get; set; }
        public bool ISTACTIVE { get; set; }
    
        public virtual ICollection<Group_User> Group_User { get; set; }
    }
}
