//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_A9_SoftwareEntities4 : DbContext
    {
        public DB_A9_SoftwareEntities4()
            : base("name=DB_A9_SoftwareEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<GROUP> GROUPs { get; set; }
        public DbSet<Group_User> Group_User { get; set; }
        public DbSet<ImageGallery> ImageGalleries { get; set; }
        public DbSet<Lookup> Lookups { get; set; }
        public DbSet<Register> Registers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int Updating_Contact()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updating_Contact");
        }
    
        public virtual int Updating_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updating_User");
        }
    }
}
