//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_User
    {
        public int Id { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<int> User_Id { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual User User { get; set; }
    }
}
